require: rubocop-rspec


AllCops:
  Exclude:
    - 'bin/*'


Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20


Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: false
