source 'https://rubygems.org'

# web application framework
gem 'sinatra', require: 'sinatra/base'
gem 'thin'

# ODM framework for MongoDB
gem 'mongoid'

# finite state machine
gem 'aasm'

# paginator
gem 'will_paginate'

# generate JSON objects with a simple DSL
gem 'jbuilder'
gem 'tilt-jbuilder', require: 'sinatra/jbuilder'
gem 'yajl-ruby', require: 'yajl'

# a configuration file format
gem 'toml-rb', require: 'toml'

# user authentication
gem 'bcrypt'
gem 'rack-jwt'

# support Cross-Origin Resource Sharing
gem 'rack-cors', group: :development

# contributed Rack middleware: Rack::PostBodyContentTypeParser, etc.
gem 'rack-contrib'

# project requirements
gem 'rake', require: false

# console
gem 'pry', require: false

# development & test
group :development, :test do
  gem 'byebug'
  gem 'pry-byebug'
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
end

# development
group :development do
  gem 'guard', require: false
  gem 'guard-rspec', require: false
end

# test
group :test do
  gem 'rspec'
  gem 'mongoid-rspec'
  gem 'database_cleaner', git: 'https://github.com/DatabaseCleaner/database_cleaner.git'
  gem 'factory_girl'
  gem 'ffaker'
  gem 'rack-test'
end
