source 'https://rubygems.org'

# web application framework
gem 'sinatra'
gem 'thin'

# ODM framework for MongoDB
gem 'mongoid'

# a configuration file format
gem 'toml-rb', require: 'toml'

# user authentication
gem 'jwt'
