source 'https://rubygems.org'

# web application framework
gem 'sinatra', require: 'sinatra/base'
gem 'thin'

# ODM framework for MongoDB
gem 'mongoid'

# a configuration file format
gem 'toml-rb', require: 'toml'

# user authentication
gem 'bcrypt'
gem 'rack-jwt'

# contributed Rack middleware
gem 'rack-contrib'

# console
gem 'pry'

# development toolkit
group :development, :test do
  gem 'pry-byebug'
  gem 'rubocop'
end
