guard :rspec, cmd: 'bundle exec rspec' do
  require 'guard/rspec/dsl'
  dsl = Guard::RSpec::Dsl.new(self)

  # RSpec files
  rspec = dsl.rspec
  watch(rspec.spec_helper) { rspec.spec_dir }
  watch(rspec.spec_files)

  # Sinatra files
  watch(%r{app/app\.rb}) { "#{rspec.spec_dir}/controllers" }
  watch(%r{app/models/(.+)\.rb}) { |m| "#{rspec.spec_dir}/models/#{m[1]}_spec.rb" }
  watch(%r{app/controllers/(.+)\.rb}) { |m| "#{rspec.spec_dir}/controllers/#{m[1]}_spec.rb" }
end
